// The logo files are the website's own, generated by branding/generate.mjs, so the two headers
// cannot drift apart.
import logoDark from "../../../website/src/assets/logo-dark.svg?url";
import logoLight from "../../../website/src/assets/logo-light.svg?url";
import { SITE_ROOT } from "../paths.ts";
import type { Theme } from "../theme.ts";

/**
 * The website's header: the NX logo linking home, and the site links, with Playground marked as
 * the current page. The website's pages are on the same origin, so its links are plain paths.
 */
export function SiteHeader({ theme }: { theme: Theme }) {
  return (
    <header className="site-header">
      <a className="site-title" href="/" aria-label="NX home">
        <img src={theme === "dark" ? logoDark : logoLight} alt="NX" width={40} height={20} />
        <span className="site-subtitle">Playground</span>
      </a>
      <nav className="site-links" aria-label="Site">
        <a href="/tutorials/getting-started/">Docs</a>
        <a href={SITE_ROOT} aria-current="page">
          Playground
        </a>
        <a className="github" href="https://github.com/nx-lang/nx" aria-label="GitHub">
          <svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" fill="currentColor">
            <path d="M12 .3a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2c-3.3.7-4-1.6-4-1.6-.6-1.4-1.4-1.8-1.4-1.8-1-.7.1-.7.1-.7 1.2 0 1.9 1.2 1.9 1.2 1 1.8 2.8 1.3 3.5 1 0-.8.4-1.3.7-1.6-2.7-.3-5.5-1.3-5.5-6 0-1.2.5-2.3 1.3-3.1-.2-.4-.6-1.6 0-3.2 0 0 1-.3 3.4 1.2a11.5 11.5 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.6 1.6.2 2.8.1 3.2.8.8 1.3 1.9 1.3 3.2 0 4.6-2.8 5.6-5.5 5.9.5.4.9 1.1.9 2.3v3.3c0 .3.1.7.8.6A12 12 0 0 0 12 .3" />
          </svg>
        </a>
      </nav>
    </header>
  );
}
