[package]
name = "nx-codegen"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
nx-api = { path = "../nx-api" }
nx-diagnostics = { path = "../nx-diagnostics" }
nx-hir = { path = "../nx-hir" }
nx-interpreter = { path = "../nx-interpreter" }
nx-types = { path = "../nx-types" }
rustc-hash = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = "3"
