#ifndef NX_FFI_H
#define NX_FFI_H

/* This file is generated by tools/generate-nx-ffi-header.sh or tools/generate-nx-ffi-header.ps1. */

#include <stddef.h>
#include <stdint.h>

#ifdef _WIN32
#define NX_FFI_EXPORT __declspec(dllimport)
#else
#define NX_FFI_EXPORT
#endif


#define NX_FFI_ABI_VERSION 13

enum NxEvalStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NxEvalStatus_Ok = 0,
  NxEvalStatus_Error = 1,
  NxEvalStatus_InvalidArgument = 2,
  NxEvalStatus_Panic = 255,
};
#ifndef __cplusplus
typedef uint32_t NxEvalStatus;
#endif // __cplusplus

enum NxOutputFormat
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NxOutputFormat_MessagePack = 0,
  NxOutputFormat_Json = 1,
};
#ifndef __cplusplus
typedef uint32_t NxOutputFormat;
#endif // __cplusplus

typedef struct NxLibraryRegistryHandle NxLibraryRegistryHandle;

typedef struct NxProgramArtifactHandle NxProgramArtifactHandle;

typedef struct NxProgramBuildContextHandle NxProgramBuildContextHandle;

typedef struct NxBuffer {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} NxBuffer;

typedef struct NxWorkspaceModule {
  const uint8_t *identity_ptr;
  size_t identity_len;
  const uint8_t *source_utf8_ptr;
  size_t source_utf8_len;
  /**
   * The module's version string as UTF-8; a zero length is no version.
   */
  const uint8_t *version_ptr;
  size_t version_len;
} NxWorkspaceModule;

/**
 * One borrowed UTF-8 string, such as a workspace identity in an implicit-import list.
 */
typedef struct NxUtf8Slice {
  const uint8_t *ptr;
  size_t len;
} NxUtf8Slice;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

NX_FFI_EXPORT uint32_t nx_ffi_abi_version(void);

NX_FFI_EXPORT void nx_free_buffer(struct NxBuffer buffer);

NX_FFI_EXPORT
NxEvalStatus nx_eval_source(const uint8_t *source_ptr,
                            size_t source_len,
                            const uint8_t *file_name_ptr,
                            size_t file_name_len,
                            uint32_t output_format,
                            struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_build_program_artifact(const struct NxProgramBuildContextHandle *build_context_ptr,
                                       const uint8_t *source_ptr,
                                       size_t source_len,
                                       const uint8_t *file_name_ptr,
                                       size_t file_name_len,
                                       struct NxProgramArtifactHandle **out_handle,
                                       struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_validate_workspace(const struct NxProgramBuildContextHandle *build_context_ptr,
                                   const struct NxWorkspaceModule *modules_ptr,
                                   size_t module_count,
                                   const struct NxUtf8Slice *implicit_imports_ptr,
                                   size_t implicit_import_count,
                                   struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_build_workspace_program_artifact(const struct NxProgramBuildContextHandle *build_context_ptr,
                                                 const struct NxWorkspaceModule *modules_ptr,
                                                 size_t module_count,
                                                 const uint8_t *entry_identity_ptr,
                                                 size_t entry_identity_len,
                                                 const struct NxUtf8Slice *implicit_imports_ptr,
                                                 size_t implicit_import_count,
                                                 struct NxProgramArtifactHandle **out_handle,
                                                 struct NxBuffer *out_buffer);

NX_FFI_EXPORT NxEvalStatus nx_create_library_registry(struct NxLibraryRegistryHandle **out_handle);

NX_FFI_EXPORT void nx_free_library_registry(struct NxLibraryRegistryHandle *handle);

NX_FFI_EXPORT
NxEvalStatus nx_load_library_into_registry(const struct NxLibraryRegistryHandle *registry_ptr,
                                           const uint8_t *root_path_ptr,
                                           size_t root_path_len,
                                           struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_create_program_build_context(const struct NxLibraryRegistryHandle *registry_ptr,
                                             struct NxProgramBuildContextHandle **out_handle);

NX_FFI_EXPORT void nx_free_program_build_context(struct NxProgramBuildContextHandle *handle);

NX_FFI_EXPORT void nx_free_program_artifact(struct NxProgramArtifactHandle *handle);

NX_FFI_EXPORT
NxEvalStatus nx_eval_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                      uint32_t output_format,
                                      struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_codegen_js_program_module(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                          const uint8_t *logical_module_name_ptr,
                                          size_t logical_module_name_len,
                                          const uint8_t *runtime_import_specifier_ptr,
                                          size_t runtime_import_specifier_len,
                                          struct NxBuffer *out_buffer);

/**
 * Explains an NX IR image as text with every table index resolved.
 *
 * `image_ptr` and `image_len` describe the image. The payload is the UTF-8 text on success, or
 * the JSON diagnostics with [`NxEvalStatus::Error`] when the image is malformed, truncated or of
 * a schema version this build does not read. The image is validated before it is read, so no
 * input traps.
 */
NX_FFI_EXPORT
NxEvalStatus nx_ir_explain(const uint8_t *image_ptr,
                           size_t image_len,
                           struct NxBuffer *out_buffer);

/**
 * Emits NX IR artifacts from a program artifact.
 *
 * `options_ptr` and `options_len` describe the emit options as UTF-8 JSON, `{ "modules": [...],
 * "debug": false }` with every key optional; an empty text is the default, which emits the entry
 * module alone without its debug section. Each module's version comes from the workspace the
 * program was built from.
 *
 * The payload is an NX IR bundle: a little-endian `u32` header length, a JSON header
 * `[{ identity, metadata, offset, length }]`, zero padding to four bytes, then the images at the
 * offsets the header gives, measured from the start of the payload. On error the payload is the
 * JSON diagnostics.
 */
NX_FFI_EXPORT
NxEvalStatus nx_codegen_nx_ir(const struct NxProgramArtifactHandle *program_artifact_ptr,
                              const uint8_t *options_ptr,
                              size_t options_len,
                              struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_component_init_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                                const uint8_t *component_name_ptr,
                                                size_t component_name_len,
                                                const uint8_t *props_ptr,
                                                size_t props_len,
                                                uint32_t output_format,
                                                struct NxBuffer *out_buffer);

/**
 * Evaluates a component from a program artifact using MessagePack props/state inputs.
 *
 * Successful output is the rendered value directly in the selected format, without lifecycle
 * state snapshot, effects, or wrapper fields.
 */
NX_FFI_EXPORT
NxEvalStatus nx_component_evaluate_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                                    const uint8_t *component_name_ptr,
                                                    size_t component_name_len,
                                                    const uint8_t *props_ptr,
                                                    size_t props_len,
                                                    const uint8_t *state_ptr,
                                                    size_t state_len,
                                                    uint32_t output_format,
                                                    struct NxBuffer *out_buffer);

/**
 * Dispatches a MessagePack batch against a component snapshot from a program artifact.
 *
 * Each batch entry is either an action record the component emits, which runs the handler its
 * parent bound, or an `ActionHandlerInvocation` record `{ token, action }` that runs a handler
 * from the snapshot's rendered output, identified by the `token` its `ActionHandler` record
 * carried. The whole batch succeeds or fails together.
 *
 * Successful output carries `rendered` (the body re-rendered against the final state, with fresh
 * handler tokens), `effects`, and `state_snapshot` in the selected format.
 */
NX_FFI_EXPORT
NxEvalStatus nx_component_dispatch_actions_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                                            const uint8_t *state_snapshot_ptr,
                                                            size_t state_snapshot_len,
                                                            const uint8_t *actions_ptr,
                                                            size_t actions_len,
                                                            uint32_t output_format,
                                                            struct NxBuffer *out_buffer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NX_FFI_H */
