#ifndef NX_FFI_H
#define NX_FFI_H

/* This file is generated by tools/generate-nx-ffi-header.sh or tools/generate-nx-ffi-header.ps1. */

#include <stddef.h>
#include <stdint.h>

#ifdef _WIN32
#define NX_FFI_EXPORT __declspec(dllimport)
#else
#define NX_FFI_EXPORT
#endif


#define NX_FFI_ABI_VERSION 8

enum NxEvalStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NxEvalStatus_Ok = 0,
  NxEvalStatus_Error = 1,
  NxEvalStatus_InvalidArgument = 2,
  NxEvalStatus_Panic = 255,
};
#ifndef __cplusplus
typedef uint32_t NxEvalStatus;
#endif // __cplusplus

enum NxOutputFormat
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NxOutputFormat_MessagePack = 0,
  NxOutputFormat_Json = 1,
};
#ifndef __cplusplus
typedef uint32_t NxOutputFormat;
#endif // __cplusplus

typedef struct NxLibraryRegistryHandle NxLibraryRegistryHandle;

typedef struct NxProgramArtifactHandle NxProgramArtifactHandle;

typedef struct NxProgramBuildContextHandle NxProgramBuildContextHandle;

typedef struct NxBuffer {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} NxBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

NX_FFI_EXPORT uint32_t nx_ffi_abi_version(void);

NX_FFI_EXPORT void nx_free_buffer(struct NxBuffer buffer);

NX_FFI_EXPORT
NxEvalStatus nx_eval_source(const uint8_t *source_ptr,
                            size_t source_len,
                            const uint8_t *file_name_ptr,
                            size_t file_name_len,
                            uint32_t output_format,
                            struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_build_program_artifact(const struct NxProgramBuildContextHandle *build_context_ptr,
                                       const uint8_t *source_ptr,
                                       size_t source_len,
                                       const uint8_t *file_name_ptr,
                                       size_t file_name_len,
                                       struct NxProgramArtifactHandle **out_handle,
                                       struct NxBuffer *out_buffer);

NX_FFI_EXPORT NxEvalStatus nx_create_library_registry(struct NxLibraryRegistryHandle **out_handle);

NX_FFI_EXPORT void nx_free_library_registry(struct NxLibraryRegistryHandle *handle);

NX_FFI_EXPORT
NxEvalStatus nx_load_library_into_registry(const struct NxLibraryRegistryHandle *registry_ptr,
                                           const uint8_t *root_path_ptr,
                                           size_t root_path_len,
                                           struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_create_program_build_context(const struct NxLibraryRegistryHandle *registry_ptr,
                                             struct NxProgramBuildContextHandle **out_handle);

NX_FFI_EXPORT void nx_free_program_build_context(struct NxProgramBuildContextHandle *handle);

NX_FFI_EXPORT void nx_free_program_artifact(struct NxProgramArtifactHandle *handle);

NX_FFI_EXPORT
NxEvalStatus nx_eval_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                      uint32_t output_format,
                                      struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_component_init_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                                const uint8_t *component_name_ptr,
                                                size_t component_name_len,
                                                const uint8_t *props_ptr,
                                                size_t props_len,
                                                uint32_t output_format,
                                                struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_component_dispatch_actions_program_artifact(const struct NxProgramArtifactHandle *program_artifact_ptr,
                                                            const uint8_t *state_snapshot_ptr,
                                                            size_t state_snapshot_len,
                                                            const uint8_t *actions_ptr,
                                                            size_t actions_len,
                                                            uint32_t output_format,
                                                            struct NxBuffer *out_buffer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NX_FFI_H */
