#ifndef NX_FFI_H
#define NX_FFI_H

/* This file is generated by tools/generate-nx-ffi-header.sh or tools/generate-nx-ffi-header.ps1. */

#include <stddef.h>
#include <stdint.h>

#ifdef _WIN32
#define NX_FFI_EXPORT __declspec(dllimport)
#else
#define NX_FFI_EXPORT
#endif


#define NX_FFI_ABI_VERSION 1

enum NxEvalStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  NxEvalStatus_Ok = 0,
  NxEvalStatus_Error = 1,
  NxEvalStatus_InvalidArgument = 2,
  NxEvalStatus_Panic = 255,
};
#ifndef __cplusplus
typedef uint32_t NxEvalStatus;
#endif // __cplusplus

typedef struct NxBuffer {
  uint8_t *ptr;
  size_t len;
  size_t cap;
} NxBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

NX_FFI_EXPORT uint32_t nx_ffi_abi_version(void);

NX_FFI_EXPORT void nx_free_buffer(struct NxBuffer buffer);

NX_FFI_EXPORT
NxEvalStatus nx_eval_source_msgpack(const uint8_t *source_ptr,
                                    size_t source_len,
                                    const uint8_t *file_name_ptr,
                                    size_t file_name_len,
                                    struct NxBuffer *out_buffer);

NX_FFI_EXPORT
NxEvalStatus nx_eval_source_json(const uint8_t *source_ptr,
                                 size_t source_len,
                                 const uint8_t *file_name_ptr,
                                 size_t file_name_len,
                                 struct NxBuffer *out_buffer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* NX_FFI_H */
