use crate::codegen::model::{
    ExportedAlias, ExportedEnum, ExportedModule, ExportedRecord, ExportedType, ExportedTypeGraph,
};
use crate::codegen::writer::CodeWriter;
use crate::codegen::{GenerateTypesOptions, GeneratedFile};
use nx_hir::ast::TypeRef;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

const NX_TYPE_DISCRIMINATOR_PROPERTY: &str = "__NxType";

pub fn emit_single_file(
    graph: &ExportedTypeGraph,
    namespace: &str,
    opts: &GenerateTypesOptions,
) -> Result<String, String> {
    let module = graph
        .modules
        .first()
        .ok_or_else(|| "Single-file generation requires one source module".to_string())?;
    Ok(render_module(graph, module, namespace, opts))
}

pub fn emit_library(
    graph: &ExportedTypeGraph,
    namespace: &str,
    opts: &GenerateTypesOptions,
) -> Result<Vec<GeneratedFile>, String> {
    let mut files = Vec::new();

    for module in &graph.modules {
        files.push(GeneratedFile {
            relative_path: module_output_path(&module.module_path),
            content: render_module(graph, module, namespace, opts),
        });
    }

    Ok(files)
}

fn render_module(
    graph: &ExportedTypeGraph,
    module: &ExportedModule,
    namespace: &str,
    opts: &GenerateTypesOptions,
) -> String {
    let mut writer = CodeWriter::new(opts.format.clone());
    write_header(&mut writer);

    if module.declarations.is_empty() {
        return writer.finish();
    }

    writer.line("using System;");
    writer.line("using MessagePack;");
    writer.line("using MessagePack.Formatters;");
    writer.blank_line();

    let global_context = CSharpRenderContext {
        namespace,
        graph,
        qualify_generated_types: true,
    };
    let namespace_context = CSharpRenderContext {
        namespace,
        graph,
        qualify_generated_types: false,
    };

    let aliases = module
        .declarations
        .iter()
        .filter_map(|declaration| match &declaration.item {
            ExportedType::Alias(alias) => Some(alias),
            _ => None,
        })
        .collect::<Vec<_>>();
    for alias in &aliases {
        emit_alias(&mut writer, alias, &global_context);
    }

    let body_items = module
        .declarations
        .iter()
        .filter(|declaration| !matches!(declaration.item, ExportedType::Alias(_)))
        .collect::<Vec<_>>();

    if !aliases.is_empty() && !body_items.is_empty() {
        writer.blank_line();
    }

    if !body_items.is_empty() {
        writer.block(
            &format!("namespace {}", sanitize_csharp_qualified_name(namespace)),
            |writer| {
                for (index, declaration) in body_items.iter().enumerate() {
                    emit_declaration(writer, &declaration.item, &namespace_context);
                    if index + 1 != body_items.len() {
                        writer.blank_line();
                    }
                }
            },
        );
    }

    writer.finish()
}

fn write_header(writer: &mut CodeWriter) {
    writer.line("// <auto-generated/>");
    writer.line("// Generated by nxlang");
    writer.line("#nullable enable");
    writer.blank_line();
}

fn emit_alias(writer: &mut CodeWriter, alias: &ExportedAlias, context: &CSharpRenderContext<'_>) {
    let alias_name = sanitize_csharp_identifier(&alias.name);
    let target_type = csharp_type(&alias.target, context);
    writer.line(&format!(
        "global using {alias_name} = {};",
        target_type.text
    ));
}

fn emit_declaration(
    writer: &mut CodeWriter,
    declaration: &ExportedType,
    context: &CSharpRenderContext<'_>,
) {
    match declaration {
        ExportedType::Alias(_) => {}
        ExportedType::Enum(enum_def) => emit_enum(writer, enum_def),
        ExportedType::Record(record) => emit_record(writer, record, context),
    }
}

fn emit_enum(writer: &mut CodeWriter, enum_def: &ExportedEnum) {
    let enum_name = sanitize_csharp_identifier(&enum_def.name);
    writer.line(&format!(
        "[MessagePackFormatter(typeof({enum_name}MessagePackFormatter))]"
    ));
    writer.block(&format!("public enum {enum_name}"), |writer| {
        for (index, member) in enum_def.members.iter().enumerate() {
            let comma = if index + 1 == enum_def.members.len() {
                ""
            } else {
                ","
            };
            writer.line(&format!("{}{}", sanitize_csharp_member_name(member), comma));
        }
    });

    writer.blank_line();
    emit_enum_messagepack_formatter(writer, enum_def);
}

fn emit_record(
    writer: &mut CodeWriter,
    record: &ExportedRecord,
    context: &CSharpRenderContext<'_>,
) {
    writer.line("[MessagePackObject]");
    let header = if let Some(base) = &record.base {
        format!(
            "public sealed class {} : {}",
            sanitize_csharp_identifier(&record.name),
            csharp_type_name(base, context).text
        )
    } else {
        format!(
            "public sealed class {}",
            sanitize_csharp_identifier(&record.name)
        )
    };

    writer.block(&header, |writer| {
        writer.line("[Key(\"$type\")]");
        writer.line(&format!(
            "public string? {NX_TYPE_DISCRIMINATOR_PROPERTY} {{ get; set; }}"
        ));

        for field in &record.fields {
            let field_type = csharp_type(&field.ty, context);
            let field_name = sanitize_csharp_member_name(&field.name);

            writer.line(&format!(
                "[Key(\"{}\")]",
                escape_csharp_string_literal(&field.name)
            ));
            if field_type.is_reference && !field_type.is_nullable {
                writer.line(&format!(
                    "public {} {} {{ get; set; }} = default!;",
                    field_type.text, field_name
                ));
            } else {
                writer.line(&format!(
                    "public {} {} {{ get; set; }}",
                    field_type.text, field_name
                ));
            }
        }
    });
}

fn emit_enum_messagepack_formatter(writer: &mut CodeWriter, enum_def: &ExportedEnum) {
    let enum_name = sanitize_csharp_identifier(&enum_def.name);
    writer.block(
        &format!(
            "public sealed class {enum_name}MessagePackFormatter : IMessagePackFormatter<{enum_name}>"
        ),
        |writer| {
            writer.block(
                &format!(
                    "public void Serialize(ref MessagePackWriter writer, {enum_name} value, MessagePackSerializerOptions options)"
                ),
                |writer| {
                    writer.line("writer.Write(ToVariantString(value));");
                },
            );

            writer.blank_line();

            writer.block(
                &format!(
                    "public {enum_name} Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)"
                ),
                |writer| {
                    writer.block("if (reader.TryReadNil())", |writer| {
                        writer.line("return default;");
                    });
                    writer.blank_line();

                    writer.block("switch (reader.NextMessagePackType)", |writer| {
                        writer.block("case MessagePackType.String:", |writer| {
                            writer.line("string variant = reader.ReadString()!;");
                            writer.line("return ParseVariant(variant);");
                        });
                        writer.block("case MessagePackType.Map:", |writer| {
                            writer.line("int count = reader.ReadMapHeader();");
                            writer.line("string? variant = null;");
                            writer.block("for (int i = 0; i < count; i++)", |writer| {
                                writer.line("string key = reader.ReadString()!;");
                                writer.block("if (key == \"$variant\")", |writer| {
                                    writer.line("variant = reader.ReadString();");
                                });
                                writer.block("else", |writer| {
                                    writer.line("reader.Skip();");
                                });
                            });
                            writer.blank_line();
                            writer.block("if (variant is null)", |writer| {
                                writer.line(
                                    "throw new MessagePackSerializationException(\"Expected NX enum map with \\\"$variant\\\".\");",
                                );
                            });
                            writer.blank_line();
                            writer.line("return ParseVariant(variant);");
                        });
                        writer.block("default:", |writer| {
                            writer.line(
                                "throw new MessagePackSerializationException(\"Expected string or map for NX enum.\");",
                            );
                        });
                    });
                },
            );

            writer.blank_line();

            writer.block(
                &format!("private static {enum_name} ParseVariant(string variant)"),
                |writer| {
                    writer.block("switch (variant)", |writer| {
                        for member in &enum_def.members {
                            let member_literal = escape_csharp_string_literal(member);
                            let member_ident = sanitize_csharp_member_name(member);
                            writer.line(&format!(
                                "case \"{member_literal}\": return {enum_name}.{member_ident};"
                            ));
                        }
                        writer.line("default:");
                        writer.line(
                            "throw new MessagePackSerializationException(\"Unknown NX enum variant.\");",
                        );
                    });
                },
            );

            writer.blank_line();

            writer.block(
                &format!("private static string ToVariantString({enum_name} value)"),
                |writer| {
                    writer.block("switch (value)", |writer| {
                        for member in &enum_def.members {
                            let member_literal = escape_csharp_string_literal(member);
                            let member_ident = sanitize_csharp_member_name(member);
                            writer.line(&format!(
                                "case {enum_name}.{member_ident}: return \"{member_literal}\";"
                            ));
                        }
                        writer.line("default:");
                        writer.line(
                            "throw new MessagePackSerializationException(\"Unknown NX enum value.\");",
                        );
                    });
                },
            );
        },
    );
}

#[derive(Clone, Debug)]
struct CSharpType {
    text: String,
    is_reference: bool,
    is_nullable: bool,
}

struct CSharpRenderContext<'a> {
    namespace: &'a str,
    graph: &'a ExportedTypeGraph,
    qualify_generated_types: bool,
}

fn csharp_type(ty: &TypeRef, context: &CSharpRenderContext<'_>) -> CSharpType {
    let mut seen_aliases = BTreeSet::new();
    csharp_type_inner(ty, context, &mut seen_aliases)
}

fn csharp_type_inner(
    ty: &TypeRef,
    context: &CSharpRenderContext<'_>,
    seen_aliases: &mut BTreeSet<String>,
) -> CSharpType {
    match ty {
        TypeRef::Nullable(inner) => {
            let mut inner = csharp_type_inner(inner, context, seen_aliases);
            inner.text = format!("{}?", inner.text);
            inner.is_nullable = true;
            inner
        }
        TypeRef::Array(inner) => {
            let inner = csharp_type_inner(inner, context, seen_aliases);
            CSharpType {
                text: format!("{}[]", inner.text),
                is_reference: true,
                is_nullable: false,
            }
        }
        TypeRef::Function { .. } => CSharpType {
            text: "global::System.Delegate".to_string(),
            is_reference: true,
            is_nullable: false,
        },
        TypeRef::Name(name) => csharp_type_name_inner(name.as_str(), context, seen_aliases),
    }
}

fn csharp_type_name(name: &str, context: &CSharpRenderContext<'_>) -> CSharpType {
    let mut seen_aliases = BTreeSet::new();
    csharp_type_name_inner(name, context, &mut seen_aliases)
}

fn csharp_type_name_inner(
    name: &str,
    context: &CSharpRenderContext<'_>,
    seen_aliases: &mut BTreeSet<String>,
) -> CSharpType {
    match name {
        "string" => CSharpType {
            text: "string".to_string(),
            is_reference: true,
            is_nullable: false,
        },
        "i32" => CSharpType {
            text: "int".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "i64" | "int" => CSharpType {
            text: "long".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "f32" => CSharpType {
            text: "float".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "f64" | "float" => CSharpType {
            text: "double".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "bool" => CSharpType {
            text: "bool".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "void" => CSharpType {
            text: "void".to_string(),
            is_reference: false,
            is_nullable: false,
        },
        "object" | "unknown" | "error" => CSharpType {
            text: "object".to_string(),
            is_reference: true,
            is_nullable: false,
        },
        other => {
            if let Some(declaration) = context.graph.declaration(other) {
                match &declaration.item {
                    ExportedType::Alias(alias) => {
                        if !seen_aliases.insert(other.to_string()) {
                            return CSharpType {
                                text: sanitize_csharp_identifier(other),
                                is_reference: true,
                                is_nullable: false,
                            };
                        }

                        let mut alias_type =
                            csharp_type_inner(&alias.target, context, seen_aliases);
                        seen_aliases.remove(other);
                        alias_type.text = sanitize_csharp_identifier(other);
                        alias_type
                    }
                    ExportedType::Enum(_) => CSharpType {
                        text: generated_type_name(
                            other,
                            context.namespace,
                            context.qualify_generated_types,
                        ),
                        is_reference: false,
                        is_nullable: false,
                    },
                    ExportedType::Record(_) => CSharpType {
                        text: generated_type_name(
                            other,
                            context.namespace,
                            context.qualify_generated_types,
                        ),
                        is_reference: true,
                        is_nullable: false,
                    },
                }
            } else {
                CSharpType {
                    text: sanitize_csharp_qualified_name(other),
                    is_reference: true,
                    is_nullable: false,
                }
            }
        }
    }
}

fn generated_type_name(name: &str, namespace: &str, qualify: bool) -> String {
    let identifier = sanitize_csharp_identifier(name);
    if qualify {
        format!(
            "global::{}.{}",
            sanitize_csharp_qualified_name(namespace),
            identifier
        )
    } else {
        identifier
    }
}

fn module_output_path(module_path: &Path) -> PathBuf {
    module_path.with_extension("g.cs")
}

fn sanitize_csharp_qualified_name(name: &str) -> String {
    name.split('.')
        .filter(|part| !part.is_empty())
        .map(sanitize_csharp_identifier)
        .collect::<Vec<_>>()
        .join(".")
}

fn sanitize_csharp_identifier(name: &str) -> String {
    let mut out = String::new();

    for (index, ch) in name.chars().enumerate() {
        let valid = if index == 0 {
            ch == '_' || ch.is_ascii_alphabetic()
        } else {
            ch == '_' || ch.is_ascii_alphanumeric()
        };
        out.push(if valid { ch } else { '_' });
    }

    if out.is_empty() {
        "_".to_string()
    } else if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("_{out}")
    } else {
        out
    }
}

fn sanitize_csharp_member_name(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    sanitize_csharp_identifier(&out)
}

fn escape_csharp_string_literal(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}
