use crate::codegen::model::{
    ExportedAlias, ExportedEnum, ExportedModule, ExportedRecord, ExportedType, ExportedTypeGraph,
};
use crate::codegen::writer::CodeWriter;
use crate::codegen::{GenerateTypesOptions, GeneratedFile};
use nx_hir::ast::TypeRef;
use std::path::{Path, PathBuf};

pub fn emit_single_file(
    graph: &ExportedTypeGraph,
    opts: &GenerateTypesOptions,
) -> Result<String, String> {
    let module = graph
        .modules
        .first()
        .ok_or_else(|| "Single-file generation requires one source module".to_string())?;
    Ok(render_module(graph, module, opts, false))
}

pub fn emit_library(
    graph: &ExportedTypeGraph,
    opts: &GenerateTypesOptions,
) -> Result<Vec<GeneratedFile>, String> {
    let mut files = Vec::new();

    for module in &graph.modules {
        files.push(GeneratedFile {
            relative_path: module_output_path(&module.module_path),
            content: render_module(graph, module, opts, true),
        });
    }

    if !graph.modules.is_empty() {
        files.push(GeneratedFile {
            relative_path: PathBuf::from("index.ts"),
            content: render_index(graph, opts),
        });
    }

    Ok(files)
}

fn render_module(
    graph: &ExportedTypeGraph,
    module: &ExportedModule,
    opts: &GenerateTypesOptions,
    include_imports: bool,
) -> String {
    let mut writer = CodeWriter::new(opts.format.clone());
    write_header(&mut writer);

    if include_imports {
        let dependencies = graph.module_dependencies(module);
        for dependency in &dependencies {
            let names = dependency
                .type_names
                .iter()
                .map(|name| sanitize_ts_type_name(name))
                .collect::<Vec<_>>()
                .join(", ");
            let specifier = relative_module_specifier(&module.module_path, &dependency.module_path);
            writer.line(&format!("import type {{ {names} }} from \"{specifier}\";"));
        }

        if !dependencies.is_empty() && !module.declarations.is_empty() {
            writer.blank_line();
        }
    }

    for (index, declaration) in module.declarations.iter().enumerate() {
        emit_declaration(&mut writer, &declaration.item);
        if index + 1 != module.declarations.len() {
            writer.blank_line();
        }
    }

    writer.finish()
}

fn render_index(graph: &ExportedTypeGraph, opts: &GenerateTypesOptions) -> String {
    let mut writer = CodeWriter::new(opts.format.clone());
    write_header(&mut writer);

    for module in &graph.modules {
        let specifier = module_path_specifier(&module.module_path);
        writer.line(&format!("export * from \"{specifier}\";"));
    }

    writer.finish()
}

fn write_header(writer: &mut CodeWriter) {
    writer.line("// <auto-generated/>");
    writer.line("// Generated by nxlang");
    writer.blank_line();
}

fn emit_declaration(writer: &mut CodeWriter, declaration: &ExportedType) {
    match declaration {
        ExportedType::Alias(alias) => emit_alias(writer, alias),
        ExportedType::Enum(enum_def) => emit_enum(writer, enum_def),
        ExportedType::Record(record) => emit_record(writer, record),
    }
}

fn emit_alias(writer: &mut CodeWriter, alias: &ExportedAlias) {
    writer.line(&format!(
        "export type {} = {};",
        sanitize_ts_type_name(&alias.name),
        ts_type(&alias.target)
    ));
}

fn emit_enum(writer: &mut CodeWriter, enum_def: &ExportedEnum) {
    let rhs = if enum_def.members.is_empty() {
        "never".to_string()
    } else {
        enum_def
            .members
            .iter()
            .map(|member| format!("\"{}\"", escape_ts_string(member)))
            .collect::<Vec<_>>()
            .join(" | ")
    };

    writer.line(&format!(
        "export type {} = {};",
        sanitize_ts_type_name(&enum_def.name),
        rhs
    ));
}

fn emit_record(writer: &mut CodeWriter, record: &ExportedRecord) {
    let header = if let Some(base) = &record.base {
        format!(
            "export interface {} extends {}",
            sanitize_ts_type_name(&record.name),
            sanitize_ts_type_name(base)
        )
    } else {
        format!("export interface {}", sanitize_ts_type_name(&record.name))
    };

    writer.block(&header, |writer| {
        for field in &record.fields {
            let key = ts_property_key(&field.name);
            let ty = ts_type(&field.ty);
            writer.line(&format!("{key}: {ty};"));
        }
    });
}

fn ts_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Name(name) => ts_type_name(name.as_str()),
        TypeRef::Array(inner) => {
            let inner = ts_type(inner);
            let needs_parens = inner.contains('|') || inner.contains("=>");
            if needs_parens {
                format!("({inner})[]")
            } else {
                format!("{inner}[]")
            }
        }
        TypeRef::Nullable(inner) => format!("{} | null", ts_type(inner)),
        TypeRef::Function {
            params,
            return_type,
        } => {
            let params = params
                .iter()
                .enumerate()
                .map(|(index, param)| format!("arg{index}: {}", ts_type(param)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({params}) => {}", ts_type(return_type))
        }
    }
}

fn ts_type_name(name: &str) -> String {
    match name {
        "string" => "string".to_string(),
        "i32" | "i64" | "int" | "f32" | "f64" | "float" => "number".to_string(),
        "bool" => "boolean".to_string(),
        "void" => "void".to_string(),
        "object" => "unknown".to_string(),
        other => sanitize_ts_type_name(other),
    }
}

fn ts_property_key(name: &str) -> String {
    if is_ts_identifier(name) {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts_string(name))
    }
}

fn is_ts_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }

    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn sanitize_ts_type_name(name: &str) -> String {
    let mut out = String::new();

    for (index, ch) in name.chars().enumerate() {
        let valid = if index == 0 {
            ch == '_' || ch == '$' || ch.is_ascii_alphabetic()
        } else {
            ch == '_' || ch == '$' || ch.is_ascii_alphanumeric()
        };
        out.push(if valid { ch } else { '_' });
    }

    if out.is_empty() {
        "_".to_string()
    } else if out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("_{out}")
    } else {
        out
    }
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

fn module_output_path(module_path: &Path) -> PathBuf {
    module_path.with_extension("ts")
}

fn module_path_specifier(module_path: &Path) -> String {
    format!("./{}", normalize_path(module_path))
}

fn relative_module_specifier(from: &Path, to: &Path) -> String {
    let from_dir = from.parent().unwrap_or_else(|| Path::new(""));
    let from_components = from_dir
        .components()
        .map(|component| component.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>();
    let to_components = to
        .components()
        .map(|component| component.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>();

    let mut shared = 0usize;
    while shared < from_components.len()
        && shared < to_components.len()
        && from_components[shared] == to_components[shared]
    {
        shared += 1;
    }

    let mut parts = Vec::new();
    for _ in shared..from_components.len() {
        parts.push("..".to_string());
    }
    for component in &to_components[shared..] {
        parts.push(component.clone());
    }

    if parts.is_empty() {
        ".".to_string()
    } else if parts[0].starts_with('.') {
        parts.join("/")
    } else {
        format!("./{}", parts.join("/"))
    }
}

fn normalize_path(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join("/")
}
