use nx_diagnostics::Diagnostic;
use std::error::Error;
use std::fmt;
use std::path::PathBuf;

/// Runtime ABI expected by JavaScript generated by `nx-codegen`.
pub const NX_JS_RUNTIME_ABI: &str = "nx-js-runtime-v1";

/// Default host-neutral runtime module imported by generated JavaScript program modules.
pub const DEFAULT_JS_PROGRAM_MODULE_RUNTIME_IMPORT_SPECIFIER: &str = "nx:runtime";

/// Default logical module name for host-neutral JavaScript program-module output.
pub const DEFAULT_JS_PROGRAM_MODULE_NAME: &str = "nx-program";

/// Executable source target emitted by `nx-codegen`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenTarget {
    TypeScript,
    JavaScript,
}

impl CodegenTarget {
    pub fn extension(self) -> &'static str {
        match self {
            Self::TypeScript => "ts",
            Self::JavaScript => "js",
        }
    }

    pub fn is_typescript(self) -> bool {
        matches!(self, Self::TypeScript)
    }
}

/// Layout style for generated executable output.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenOutputFormat {
    Files,
}

/// Options shared by TypeScript and JavaScript executable generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenOptions {
    pub target: CodegenTarget,
    pub output_format: CodegenOutputFormat,
}

impl CodegenOptions {
    pub fn typescript() -> Self {
        Self {
            target: CodegenTarget::TypeScript,
            output_format: CodegenOutputFormat::Files,
        }
    }

    pub fn javascript() -> Self {
        Self {
            target: CodegenTarget::JavaScript,
            output_format: CodegenOutputFormat::Files,
        }
    }
}

/// Options for host-neutral JavaScript program-module generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JsProgramModuleOptions {
    pub logical_module_name: String,
    pub runtime_import_specifier: String,
}

impl JsProgramModuleOptions {
    pub fn javascript() -> Self {
        Self::default()
    }
}

impl Default for JsProgramModuleOptions {
    fn default() -> Self {
        Self {
            logical_module_name: DEFAULT_JS_PROGRAM_MODULE_NAME.to_string(),
            runtime_import_specifier: DEFAULT_JS_PROGRAM_MODULE_RUNTIME_IMPORT_SPECIFIER
                .to_string(),
        }
    }
}

/// One generated output file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub relative_path: PathBuf,
    pub content: String,
}

/// One function entrypoint exported by a generated JavaScript program module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedJsProgramModuleFunctionExport {
    pub entrypoint_name: String,
    pub export_name: String,
}

/// One concrete component and schema surface exported by a generated JavaScript program module.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedJsProgramModuleComponentExport {
    pub component_name: String,
    pub component_export_name: String,
    pub schema_export_name: String,
    pub initial_state_export_name: Option<String>,
    pub render_export_name: Option<String>,
}

/// Complete host-neutral JavaScript program-module output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedJsProgramModule {
    pub source_text: String,
    pub logical_module_name: String,
    pub runtime_import_specifier: String,
    pub runtime_abi: String,
    pub program_fingerprint: u64,
    pub function_exports: Vec<GeneratedJsProgramModuleFunctionExport>,
    pub component_exports: Vec<GeneratedJsProgramModuleComponentExport>,
}

/// Non-fatal code generation warning.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenWarning {
    pub message: String,
}

/// Complete generated executable output.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenOutput {
    pub files: Vec<GeneratedFile>,
    pub warnings: Vec<CodegenWarning>,
    pub diagnostics: Vec<Diagnostic>,
}

/// Fatal code generation failure. No executable output should be emitted when this is returned.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodegenError {
    pub diagnostics: Vec<Diagnostic>,
}

impl CodegenError {
    pub fn new(diagnostics: Vec<Diagnostic>) -> Self {
        Self { diagnostics }
    }

    pub fn single(diagnostic: Diagnostic) -> Self {
        Self {
            diagnostics: vec![diagnostic],
        }
    }
}

impl fmt::Display for CodegenError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.diagnostics.as_slice() {
            [] => write!(formatter, "code generation failed"),
            [diagnostic] => write!(formatter, "{}", diagnostic.message()),
            diagnostics => write!(
                formatter,
                "code generation failed with {} diagnostics",
                diagnostics.len()
            ),
        }
    }
}

impl Error for CodegenError {}
