//! Keeps the prelude's published surface in step with the compiler's: the image the TypeScript
//! runtime ships, and the version an image records for it.
//!
//! <para>The runtime ships the prelude so no host has to, which only works while the image it ships
//! is the one this compiler emits. The first test emits the prelude and compares it with the
//! checked-in file; set `NX_UPDATE_PRELUDE_IMAGE=1` to rewrite the file after an intended change to
//! `prelude.nx`, and review the diff.</para>
//!
//! <para>The second pins the prelude's declaration shape beside
//! [`nx_hir::PRELUDE_VERSION`](nx_hir::PRELUDE_VERSION), which is what linking compares. The
//! version is a judgement — a reworded comment is not a new contract, a renamed field is — so it
//! cannot be derived, and this is what keeps it from falling behind the declarations it stands
//! for.</para>

use crate::ir::{NxIrArtifact, NxIrEmitOptions};
use crate::ir_explain::explain_nx_ir_image;
use crate::ir_image::write_nx_ir_image;
use crate::{build_codegen_program, build_nx_ir_artifacts};
use nx_api::{build_program_artifact_from_source, ProgramBuildContext};
use std::fs;
use std::path::PathBuf;

/// Where the runtime keeps the image, relative to the repository root.
const PRELUDE_IMAGE_PATH: &str = "runtime/typescript/src/prelude-image.ts";

/// The command that rewrites the file.
const UPDATE_COMMAND: &str =
    "NX_UPDATE_PRELUDE_IMAGE=1 cargo test -p nx-codegen --lib prelude_image";

fn repository_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

/// The prelude's image, as this compiler emits it.
///
/// <para>Emitted from a program that references a prelude declaration, because the prelude is a
/// module of a program rather than a program of its own.</para>
fn emit_prelude_image() -> Vec<u8> {
    let artifact = build_program_artifact_from_source(
        "let root() = { 1..5 }",
        "prelude-image.nx",
        &ProgramBuildContext::empty(),
    )
    .expect("a program that reaches the prelude");
    let program = build_codegen_program(&artifact).expect("codegen program");
    let mut images: Vec<NxIrArtifact> = build_nx_ir_artifacts(
        &program,
        &NxIrEmitOptions {
            modules: Some(vec![nx_hir::PRELUDE_MODULE_IDENTITY.to_string()]),
            ..NxIrEmitOptions::default()
        },
    )
    .expect("the prelude's image");
    assert_eq!(images.len(), 1);
    write_nx_ir_image(&images.remove(0)).expect("image bytes")
}

/// The module the runtime imports: the image as base64 and the version it carries, with no
/// dependency of its own.
fn prelude_image_module(bytes: &[u8]) -> String {
    format!(
        "// Generated by `{UPDATE_COMMAND}`. Do not edit.\n\
         //\n\
         // The compiled image of the NX prelude ({identity}), which linking supplies for that\n\
         // identity whenever a host's resolver does not.\n\
         export const NX_PRELUDE_IMAGE_BASE64 =\n  \"{base64}\";\n\
         \n\
         // The prelude contract this image is, which every module table that lists the prelude\n\
         // records. Linking compares the two.\n\
         export const NX_PRELUDE_VERSION = \"{version}\";\n",
        identity = nx_hir::PRELUDE_MODULE_IDENTITY,
        base64 = base64(bytes),
        version = nx_hir::PRELUDE_VERSION,
    )
}

/// Standard base64, written here so the generator needs no dependency.
fn base64(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let group = chunk.iter().enumerate().fold(0u32, |group, (index, byte)| {
            group | (u32::from(*byte) << (16 - 8 * index))
        });
        for index in 0..4 {
            if index <= chunk.len() {
                out.push(char::from(
                    ALPHABET[((group >> (18 - 6 * index)) & 0x3f) as usize],
                ));
            } else {
                out.push('=');
            }
        }
    }
    out
}

#[test]
fn the_runtimes_prelude_image_is_the_one_the_compiler_emits() {
    let path = repository_root().join(PRELUDE_IMAGE_PATH);
    let expected = prelude_image_module(&emit_prelude_image());

    if std::env::var_os("NX_UPDATE_PRELUDE_IMAGE").is_some() {
        fs::create_dir_all(path.parent().expect("parent")).expect("runtime src directory");
        fs::write(&path, expected.as_bytes())
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
        return;
    }

    let actual = fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        actual,
        expected,
        "{} is out of date; run `{UPDATE_COMMAND}`",
        path.display()
    );
}

#[test]
fn base64_matches_the_standard_alphabet_and_padding() {
    assert_eq!(base64(b""), "");
    assert_eq!(base64(b"f"), "Zg==");
    assert_eq!(base64(b"fo"), "Zm8=");
    assert_eq!(base64(b"foo"), "Zm9v");
    assert_eq!(base64(b"foob"), "Zm9vYg==");
    assert_eq!(base64(b"fooba"), "Zm9vYmE=");
    assert_eq!(base64(b"foobar"), "Zm9vYmFy");
}

/// The prelude's declaration shape: its image explained, with everything that is not part of the
/// contract removed.
///
/// <para>The fingerprint hashes the source text and the spans move with it, so both would change
/// for a reworded comment. What is left is exactly what an image compiled against the prelude
/// depends on: the declarations, their fields, and the field types.</para>
fn prelude_declaration_shape() -> String {
    let explained = explain_nx_ir_image(&emit_prelude_image()).expect("the prelude explains");
    explained
        .lines()
        .filter(|line| !line.starts_with("module "))
        .map(|line| match line.split_once(" @") {
            Some((head, _span)) => head,
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

#[test]
fn the_prelude_declaration_shape_is_pinned_to_the_prelude_version() {
    // Bump `nx_hir::PRELUDE_VERSION` and update this snapshot together whenever a declaration
    // below changes: an image that named the old shape must not link against the new prelude.
    let expected = "\
requires update-records-v1 property-unions-v1
entrypoints functions [] components []

record Range
  start: object required
  end: object required
  endInclusive: boolean required

record Range.Update update of Range
  start: object
  end: object
  endInclusive: boolean

union Range.Property property of Range
  case start constant
  case end constant
  case endInclusive constant";

    assert_eq!(
        prelude_declaration_shape(),
        expected,
        "the prelude's declarations changed; bump `nx_hir::PRELUDE_VERSION` (now \"{}\") and \
         update this snapshot",
        nx_hir::PRELUDE_VERSION
    );
}
